# This uses newer and faster docker based build system
# Based on https://github.com/Koodimonni/wordpress-test-template

sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

services:
  - mysql

php:
  - nightly
  - 7.3
  - 7.2

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  allow_failures:
    - php: nightly

before_install:
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'

install:
#  - sudo apt-get update
#  - sudo apt-get install libsodium-dev
  - wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
  - chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
before_script:
  - git clone https://github.com/kalaspuffar/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - phpcs --standard=rulesset.xml ./sqrl-login.php
  - phpunit
  - php coverage-checker.php clover.xml 20
